apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  selector:
    matchLabels:
    {{- range $x,$y := .Values.labels }}
      {{ $x }}: {{ $y }}
    {{- end }}
  template:
    metadata:
      labels:
      {{- range $x,$y := .Values.labels }}
        {{ $x }}: {{ $y }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Values.name }}-container
        image: {{ .Values.pod.image }}:{{ .Values.pod.tag }}
        imagePullPolicy: {{ .Values.pod.pullPolicy }}
        env:
        {{- with .Values.env }}
          - name: DB_NAME
            value: {{ .DB_NAME }}
          - name: DB_USER
            value: {{ .DB_USER }}
          - name: DB_PASSWD
            value: {{ .DB_PASSWD }}
          - name: DB_HOST
            value: {{ .DB_HOST }}
        {{- end }}
        resources:
        {{- with .Values.resources }}
        {{- with .limits }}
          limits:
            memory: {{ .mem }}
            cpu: {{ .cpu }}
        {{- end }}
        {{- with .requests }}
          requests:
            memory: {{ .mem }}
            cpu: {{ .cpu }}
        {{- end }}
        {{- end }}
        ports:
        - name: {{ .Values.appPort.name }}
          containerPort: {{ .Values.appPort.port }}
